name: Activar IPTV

on:
  schedule:
    # Ejecuta el flujo de trabajo cada 5 horas
    - cron: '0 */5 * * *'

  workflow_dispatch:

jobs:
  activar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Extrae tu repositorio en el entorno de ejecución del flujo de trabajo

    - name: Configurar Git
      run: |
        git config --global user.email "elselloweb@gmail.com"
        git config --global user.name "ElSelloTV"
      # Configura Git (ajusta con tu información)

    - name: Ejecutar script de activación
      run: |
        chmod +x ./activar.sh
        ./activar.sh
      # Asegúrate de que tu script es ejecutable y luego ejecútalo

    # Agrega cualquier paso adicional que necesites aquí
